### ISSUE TITLE
logging does not work in custom gradle plugins

### ISSUE THREAD

**Issue by paddy3k** [ljacomet/logging-capabilities#34]
Hello,

I can't get the plugin to work in my own custom gradle plugin. I configured it this way:

**build.gradle**

```gradle
plugins {
    id 'groovy'
    id 'groovy-gradle-plugin'
    id 'maven-publish'
    id  'dev.jacomet.logging-capabilities' version '0.11.0'
}

loggingCapabilities {
    enforceLog4J2()
}

dependencies {
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.17.2'
}
```

This is the task part in my plugin class:

```groovy
import org.slf4j.LoggerFactory
...
project.tasks.register('log-test') {
      Logger logger = LoggerFactory.getLogger(DemoPlugin.class)

      logger.info('##### INFO #####')
      logger.error('##### ERROR #####')
      logger.debug('##### DEBUG #####')
}
```

I only get the error output in the console:

```bash
12:40:27: Executing 'log-test'...

Starting Gradle Daemon...
Connected to the target VM, address: '127.0.0.1:49774', transport: 'socket'
Gradle Daemon started in 1 s 361 ms
##### ERROR #####
> Task :testproject:log-test UP-TO-DATE

BUILD SUCCESSFUL in 15s
8 actionable tasks: 8 up-to-date
12:40:43: Execution finished 'log-test'.
Disconnected from the target VM, address: '127.0.0.1:49774', transport: 'socket'
```

I put a breakpoint on the StaticLoggerBinder class to inspect which implementation is used. It seems that the gradle default is used, instead of the log4j one:

![Screenshot 2023-03-11 230521](https://user-images.githubusercontent.com/31168279/224543116-242423f7-6418-4b9a-8116-3469c233d426.png)

In a normal application project I have no problems. Only plugin-projects are affected. I also found this thread about the issue:

https://discuss.gradle.org/t/logging-in-gradle-plugin/31685/5

**Comment by ljacomet** [comment]
Gradle plugins need to be considered as running in a specific context. You should be relying on Gradle logging instead of attempting to use a different system.

The fact that you only see the error message in the log is because `ERROR` is the only level that is above `LIFECYCLE` in your test. And the output of Gradle defaults to `LIFECYCLE`.
You should be able to see the other output by setting the Gradle output level in your test with `-i` or `-d` respectively.

I will close this issue as this plugin does not have a specific integration for controlling logging in Gradle plugins themselves.
